# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PPPgui.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChipPressureTest(object):
    def setupUi(self, ChipPressureTest):
        ChipPressureTest.setObjectName("ChipPressureTest")
        ChipPressureTest.resize(1132, 861)
        self.centralwidget = QtWidgets.QWidget(ChipPressureTest)
        self.centralwidget.setObjectName("centralwidget")
        self.InitRobot = QtWidgets.QPushButton(self.centralwidget)
        self.InitRobot.setGeometry(QtCore.QRect(30, 10, 181, 51))
        self.InitRobot.setObjectName("InitRobot")
        self.HomeRobot = QtWidgets.QPushButton(self.centralwidget)
        self.HomeRobot.setGeometry(QtCore.QRect(240, 10, 171, 51))
        self.HomeRobot.setObjectName("HomeRobot")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(570, 90, 131, 191))
        self.label_5.setStyleSheet("image: url(:/newPrefix/pppbacker.JPG);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(700, 80, 131, 211))
        self.label_6.setStyleSheet("image: url(:/newPrefix/pppbacker.JPG);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(830, 80, 131, 211))
        self.label_7.setStyleSheet("image: url(:/newPrefix/pppbacker.JPG);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(960, 80, 131, 211))
        self.label_8.setStyleSheet("image: url(:/newPrefix/pppbacker.JPG);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(0, 90, 131, 191))
        self.label_9.setStyleSheet("image: url(:/newPrefix/pppbacker.JPG);")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(390, 80, 131, 211))
        self.label_10.setStyleSheet("image: url(:/newPrefix/pppbacker.JPG);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(130, 80, 131, 211))
        self.label_11.setStyleSheet("image: url(:/newPrefix/pppbacker.JPG);")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(260, 80, 131, 211))
        self.label_12.setStyleSheet("image: url(:/newPrefix/pppbacker.JPG);")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(570, 280, 131, 191))
        self.label_13.setStyleSheet("image: url(:/newPrefix/pppbacker.JPG);")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(960, 270, 131, 211))
        self.label_14.setStyleSheet("image: url(:/newPrefix/pppbacker.JPG);")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(700, 270, 131, 211))
        self.label_15.setStyleSheet("image: url(:/newPrefix/pppbacker.JPG);")
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(830, 270, 131, 211))
        self.label_16.setStyleSheet("image: url(:/newPrefix/pppbacker.JPG);")
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(390, 270, 131, 211))
        self.label_17.setStyleSheet("image: url(:/newPrefix/pppbacker.JPG);")
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(130, 270, 131, 211))
        self.label_18.setStyleSheet("image: url(:/newPrefix/pppbacker.JPG);")
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(0, 280, 131, 191))
        self.label_19.setStyleSheet("image: url(:/newPrefix/pppbacker.JPG);")
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(260, 270, 131, 211))
        self.label_20.setStyleSheet("image: url(:/newPrefix/pppbacker.JPG);")
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.checkBox_chip16 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_chip16.setGeometry(QtCore.QRect(990, 280, 92, 23))
        self.checkBox_chip16.setObjectName("checkBox_chip16")
        self.checkBox_chip14 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_chip14.setGeometry(QtCore.QRect(730, 280, 92, 23))
        self.checkBox_chip14.setObjectName("checkBox_chip14")
        self.checkBox_chip15 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_chip15.setGeometry(QtCore.QRect(860, 280, 92, 23))
        self.checkBox_chip15.setObjectName("checkBox_chip15")
        self.checkBox_chip13 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_chip13.setGeometry(QtCore.QRect(600, 280, 92, 23))
        self.checkBox_chip13.setObjectName("checkBox_chip13")
        self.checkBox_chip12 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_chip12.setGeometry(QtCore.QRect(420, 280, 92, 23))
        self.checkBox_chip12.setObjectName("checkBox_chip12")
        self.checkBox_chip11 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_chip11.setGeometry(QtCore.QRect(290, 280, 92, 23))
        self.checkBox_chip11.setObjectName("checkBox_chip11")
        self.checkBox_chip10 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_chip10.setGeometry(QtCore.QRect(160, 280, 92, 23))
        self.checkBox_chip10.setObjectName("checkBox_chip10")
        self.checkBox_chip9 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_chip9.setGeometry(QtCore.QRect(30, 280, 92, 23))
        self.checkBox_chip9.setObjectName("checkBox_chip9")
        self.Exit = QtWidgets.QPushButton(self.centralwidget)
        self.Exit.setGeometry(QtCore.QRect(940, 10, 171, 51))
        self.Exit.setObjectName("Exit")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 510, 1081, 291))
        self.textBrowser.setObjectName("textBrowser")
        self.results = QtWidgets.QLabel(self.centralwidget)
        self.results.setGeometry(QtCore.QRect(20, 480, 67, 17))
        self.results.setObjectName("results")
        self.checkBox_chip1 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_chip1.setGeometry(QtCore.QRect(30, 90, 92, 23))
        self.checkBox_chip1.setObjectName("checkBox_chip1")
        self.RunTest = QtWidgets.QPushButton(self.centralwidget)
        self.RunTest.setGeometry(QtCore.QRect(440, 10, 471, 51))
        self.RunTest.setObjectName("RunTest")
        self.checkBox_chip2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_chip2.setGeometry(QtCore.QRect(160, 90, 92, 23))
        self.checkBox_chip2.setObjectName("checkBox_chip2")
        self.checkBox_chip3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_chip3.setGeometry(QtCore.QRect(290, 90, 92, 23))
        self.checkBox_chip3.setObjectName("checkBox_chip3")
        self.checkBox_chip4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_chip4.setGeometry(QtCore.QRect(420, 90, 92, 23))
        self.checkBox_chip4.setObjectName("checkBox_chip4")
        self.checkBox_chip5 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_chip5.setGeometry(QtCore.QRect(600, 90, 92, 23))
        self.checkBox_chip5.setObjectName("checkBox_chip5")
        self.checkBox_chip6 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_chip6.setGeometry(QtCore.QRect(730, 90, 92, 23))
        self.checkBox_chip6.setObjectName("checkBox_chip6")
        self.checkBox_chip7 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_chip7.setGeometry(QtCore.QRect(860, 90, 92, 23))
        self.checkBox_chip7.setObjectName("checkBox_chip7")
        self.checkBox_chip8 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_chip8.setGeometry(QtCore.QRect(990, 90, 92, 23))
        self.checkBox_chip8.setObjectName("checkBox_chip8")
        ChipPressureTest.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ChipPressureTest)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1132, 22))
        self.menubar.setObjectName("menubar")
        self.menuPPP_Pressure_Test = QtWidgets.QMenu(self.menubar)
        self.menuPPP_Pressure_Test.setObjectName("menuPPP_Pressure_Test")
        ChipPressureTest.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ChipPressureTest)
        self.statusbar.setObjectName("statusbar")
        ChipPressureTest.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuPPP_Pressure_Test.menuAction())

        self.retranslateUi(ChipPressureTest)
        QtCore.QMetaObject.connectSlotsByName(ChipPressureTest)

    def retranslateUi(self, ChipPressureTest):
        _translate = QtCore.QCoreApplication.translate
        ChipPressureTest.setWindowTitle(_translate("ChipPressureTest", "MainWindow"))
        self.InitRobot.setText(_translate("ChipPressureTest", "Init Robot"))
        self.HomeRobot.setText(_translate("ChipPressureTest", "Home Robot"))
        self.checkBox_chip16.setText(_translate("ChipPressureTest", "Chip 16"))
        self.checkBox_chip14.setText(_translate("ChipPressureTest", "Chip 14"))
        self.checkBox_chip15.setText(_translate("ChipPressureTest", "Chip 15"))
        self.checkBox_chip13.setText(_translate("ChipPressureTest", "Chip 13"))
        self.checkBox_chip12.setText(_translate("ChipPressureTest", "Chip 12"))
        self.checkBox_chip11.setText(_translate("ChipPressureTest", "Chip 11"))
        self.checkBox_chip10.setText(_translate("ChipPressureTest", "Chip 10"))
        self.checkBox_chip9.setText(_translate("ChipPressureTest", "Chip 9"))
        self.Exit.setText(_translate("ChipPressureTest", "Exit"))
        self.results.setText(_translate("ChipPressureTest", "Results:"))
        self.checkBox_chip1.setText(_translate("ChipPressureTest", "Chip 1"))
        self.RunTest.setText(_translate("ChipPressureTest", "Run Test"))
        self.checkBox_chip2.setText(_translate("ChipPressureTest", "Chip 2"))
        self.checkBox_chip3.setText(_translate("ChipPressureTest", "Chip 3"))
        self.checkBox_chip4.setText(_translate("ChipPressureTest", "Chip 4"))
        self.checkBox_chip5.setText(_translate("ChipPressureTest", "Chip 5"))
        self.checkBox_chip6.setText(_translate("ChipPressureTest", "Chip 6"))
        self.checkBox_chip7.setText(_translate("ChipPressureTest", "Chip 7"))
        self.checkBox_chip8.setText(_translate("ChipPressureTest", "Chip 8"))
        self.menuPPP_Pressure_Test.setTitle(_translate("ChipPressureTest", "PPP Pressure Test"))
        self.InitRobot.clicked.connect(self.btn_type())

    def btn_type(self):
        self.InitRobot.setObjectName('ho')

#import testing_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ChipPressureTest = QtWidgets.QMainWindow()
    ui = Ui_ChipPressureTest()
    ui.setupUi(ChipPressureTest)
    ChipPressureTest.show()
    sys.exit(app.exec_())
